import type { CharacterId } from './characters';
import type { CategoryKey } from './categories';

export type ItemCharacter = CharacterId | 'both';

export interface Item {
  id: string;
  name_jp: string;
  character: ItemCharacter;
  category: CategoryKey;
  series_id: string;
  price_jpy: number; // 點數兌換商品填 0
  manufacturer: string;
  release_date: string; // 'YYYY/MM/DD'
  image_cover: string;
  owned: boolean;
  notes: string | null;
}

export const ITEMS: Item[] = [
  // ── ufotable 2025 生日系列 ─────────────────────────────────────────────

  {
    id: 'shinobu-acrylic-2025-birthday',
    name_jp: '2025 胡蝶しのぶの誕生日 立体アクリルスタンド',
    character: 'shinobu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 2400,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'shinobu-acrylic-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-badge-2025-birthday',
    name_jp: '2025 胡蝶しのぶの誕生日 ロゼット',
    character: 'shinobu',
    category: 'badge',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 1300,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'shinobu-badge-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-coaster-2025-birthday',
    name_jp: '2025 胡蝶しのぶの誕生日 畳コースター',
    character: 'shinobu',
    category: 'coaster',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 750,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'shinobu-coaster-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-charm-2025-birthday',
    name_jp: '2025 胡蝶しのぶの誕生日 和菓子バックチャーム',
    character: 'shinobu',
    category: 'charm',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 3200,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'shinobu-charm-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-acrylic-pop-2025-birthday',
    name_jp: '2025 胡蝶しのぶの誕生日 スタンディPOP',
    character: 'shinobu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 4500,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'shinobu-acrylic-pop-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-box-2025-birthday',
    name_jp: '2025 胡蝶しのぶの誕生日 お誕生日BOX',
    character: 'shinobu',
    category: 'set',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 10000,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'shinobu-box-birthday-2025-cover.jpg',
    owned: false,
    notes: 'ufotableWEBSHOP限定',
  },
  {
    id: 'shinobu-sticker-2025-birthday',
    name_jp: '2025 胡蝶しのぶの誕生日 ダイカットステッカー',
    character: 'shinobu',
    category: 'sticker',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'shinobu-sticker-birthday-2025-cover.webp',
    owned: false,
    notes: 'ポイント景品，ポイント数交換',
  },
  {
    id: 'giyu-acrylic-2025-birthday',
    name_jp: '2025 冨岡義勇の誕生日 立体アクリルスタンド',
    character: 'giyu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 2400,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'giyu-acrylic-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'giyu-badge-2025-birthday',
    name_jp: '2025 冨岡義勇の誕生日 ロゼット',
    character: 'giyu',
    category: 'badge',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 1300,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'giyu-badge-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'giyu-coaster-2025-birthday',
    name_jp: '2025 冨岡義勇の誕生日 畳コースター',
    character: 'giyu',
    category: 'coaster',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 750,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'giyu-coaster-birthday-2025-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'giyu-charm-2025-birthday',
    name_jp: '2025 冨岡義勇の誕生日 和菓子バックチャーム',
    character: 'giyu',
    category: 'charm',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 3200,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'giyu-charm-birthday-2025-cover.webp',
    owned: false,
    notes: 'ufotable DINING各店舗販売限定',
  },
  {
    id: 'giyu-acrylic-pop-2025-birthday',
    name_jp: '2025 冨岡義勇の誕生日 スタンディPOP',
    character: 'giyu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2025/02/08',
    image_cover: 'giyu-acrylic-pop-birthday-2025-cover.webp',
    owned: false,
    notes: 'ufotable DINING各店舗販売限定',
  },
  {
    id: 'giyu-box-2025-birthday',
    name_jp: '2025 冨岡義勇の誕生日 お誕生日BOX【数量限定】',
    character: 'giyu',
    category: 'set',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 10000,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'giyu-box-birthday-2025-cover.jpg',
    owned: false,
    notes: 'ufotableWEBSHOP限定',
  },
  {
    id: 'giyu-sticker-2025-birthday',
    name_jp: '2025 冨岡義勇の誕生日 ダイカットステッカー',
    character: 'giyu',
    category: 'sticker',
    series_id: 'ufotable-birthday-2025',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2025/02/24',
    image_cover: 'giyu-sticker-birthday-2025-cover.webp',
    owned: false,
    notes: 'ポイント景品，ポイント数交換',
  },

  // ── ufotable 2026 生日系列 ─────────────────────────────────────────────

  {
    id: 'shinobu-acrylic-2026-birthday',
    name_jp: '2026 胡蝶しのぶの誕生日 ジオラマアクリルスタンド',
    character: 'shinobu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 1950,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'shinobu-acrylic-birthday-2026-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-badge-2026-birthday',
    name_jp: '2026 胡蝶しのぶの誕生日 ロゼット',
    character: 'shinobu',
    category: 'badge',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 1300,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'shinobu-badge-birthday-2026-cover.webp',
    owned: false,
    notes: null,
  },
  // TODO: shinobu-card-sleeve-2026-birthday — name 截斷、多欄缺失，請補齊後取消此註解
  // {
  //   id: 'shinobu-card-sleeve-2026-birthday',
  //   name_jp: '',
  //   character: 'shinobu',
  //   category: 'card sleeve',
  //   series_id: 'ufotable-birthday-2026',
  //   price_jpy: 0,
  //   manufacturer: 'ufotable',
  //   release_date: '2026/02/24',
  //   image_cover: '',
  //   owned: false,
  //   notes: null,
  // },
  {
    id: 'shinobu-drink-sleeve-2026-birthday',
    name_jp: '2026 胡蝶しのぶの誕生日 ドリンクスリーブ',
    character: 'shinobu',
    category: 'cup sleeve',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 1850,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'shinobu-drink-sleeve-birthday-2026-cover.webp',
    owned: false,
    notes: 'ufotable DINING、DINING HIROMA、CINEMA、TOGO限定',
  },
  {
    id: 'shinobu-sticker-2026-birthday',
    name_jp: '2026 胡蝶しのぶの誕生日 ステッカー',
    character: 'shinobu',
    category: 'sticker',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'shinobu-sticker-birthday-2026-cover.webp',
    owned: false,
    notes: 'ポイント景品，ポイント数交換',
  },
  {
    id: 'shinobu-box-2026-birthday',
    name_jp: '2026 胡蝶しのぶの誕生日 お誕生日ボックス',
    character: 'shinobu',
    category: 'set',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 10000,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'shinobu-box-birthday-2026-cover.webp',
    owned: false,
    notes: 'ufotableWEBSHOP限定',
  },
  {
    id: 'giyu-acrylic-2026-birthday',
    name_jp: '2026 冨岡義勇の誕生日 ジオラマアクリルスタンド',
    character: 'giyu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 1950,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'giyu-acrylic-birthday-2026-cover.webp',
    owned: false,
    notes: null,
  },
  // TODO: giyu-badge-2026-birthday — character 截斷、image 可能有誤，請補齊後取消此註解
  // {
  //   id: 'giyu-badge-2026-birthday',
  //   name_jp: '2026 冨岡義勇の誕生日 ロゼット',
  //   character: 'giyu',
  //   category: 'badge',
  //   series_id: 'ufotable-birthday-2026',
  //   price_jpy: 1300,
  //   manufacturer: 'ufotable',
  //   release_date: '2026/02/24',
  //   image_cover: '',
  //   owned: false,
  //   notes: null,
  // },
  {
    id: 'giyu-bag-2026-birthday',
    name_jp: '2026 冨岡義勇の誕生日 バースデートートバッグ',
    character: 'giyu',
    category: 'bag',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 2300,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'giyu-bag-birthday-2026-cover.webp',
    owned: false,
    notes: null,
  },
  {
    id: 'giyu-drink-sleeve-2026-birthday',
    name_jp: '2026 冨岡義勇の誕生日 ドリンクスリーブ',
    character: 'giyu',
    category: 'cup sleeve',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 1850,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'giyu-drink-sleeve-birthday-2026-cover.webp',
    owned: false,
    notes: 'ufotable DINING、DINING HIROMA、CINEMA、TOGO限定',
  },
  {
    id: 'giyu-sticker-2026-birthday',
    name_jp: '2026 冨岡義勇の誕生日 ステッカー',
    character: 'giyu',
    category: 'sticker',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'giyu-sticker-birthday-2026-cover.webp',
    owned: false,
    notes: 'ポイント景品，ポイント数交換',
  },
  {
    id: 'giyu-box-2026-birthday',
    name_jp: '2026 冨岡義勇の誕生日 お誕生日ボックス',
    character: 'giyu',
    category: 'set',
    series_id: 'ufotable-birthday-2026',
    price_jpy: 10000,
    manufacturer: 'ufotable',
    release_date: '2026/02/24',
    image_cover: 'giyu-box-birthday-2026-cover.webp',
    owned: false,
    notes: 'ufotableWEBSHOP限定',
  },

  // ── ufotable 2024 生日系列 ─────────────────────────────────────────────

  // TODO: shinobu-acrylic-2024-birthday + shinobu-badge-2024-birthday — 兩筆合併，請分開補齊後取消此註解
  // { id: 'shinobu-acrylic-2024-birthday', ... },
  // { id: 'shinobu-badge-2024-birthday', ... },
  {
    id: 'shinobu-card-sleeve-2024-birthday',
    name_jp: '2024 胡蝶しのぶの誕生日 アクリルブロマイドホルダー',
    character: 'shinobu',
    category: 'card sleeve',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 2000,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'shinobu-card-sleeve-birthday-2024-cover.jpg',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-bag-2024-birthday',
    name_jp: '2024 胡蝶しのぶの誕生日 ケーキ型ポーチ',
    character: 'shinobu',
    category: 'bag',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 1500,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'shinobu-bag-birthday-2024-cover.jpg',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-decoration-2024-birthday',
    name_jp: '2024 胡蝶しのぶの誕生日 スティックバルーン',
    character: 'shinobu',
    category: 'decoration',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 850,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'shinobu-decoration-birthday-2024-cover.jpg',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-box-2024-birthday',
    name_jp: '2024 胡蝶しのぶの誕生日 お誕生日BOX',
    character: 'shinobu',
    category: 'set',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 10000,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'shinobu-box-birthday-2024-cover.jpg',
    owned: false,
    notes: 'ufotableWEBSHOP限定',
  },
  // TODO: shinobu-acrylic-pop-2024-birthday + shinobu-sticker-2024-birthday — 兩筆合併，請分開補齊後取消此註解
  // { id: 'shinobu-acrylic-pop-2024-birthday', ... },
  // { id: 'shinobu-sticker-2024-birthday', ... },
  {
    id: 'shinobu-melamine-2024-birthday',
    name_jp: '2024 胡蝶しのぶの誕生日 メラミンプレート',
    character: 'shinobu',
    category: 'melamine',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'shinobu-melamine-birthday-2024-cover.jpg',
    owned: false,
    notes: 'ポイント景品，ポイント数交換',
  },
  {
    id: 'giyu-acrylic-2024-birthday',
    name_jp: '2024 冨岡義勇の誕生日 アクリルスタンド',
    character: 'giyu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 1800,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'giyu-acrylic-birthday-2024-cover.jpg',
    owned: false,
    notes: null,
  },
  {
    id: 'giyu-badge-2024-birthday',
    name_jp: '2024 冨岡義勇の誕生日 ロゼット',
    character: 'giyu',
    category: 'badge',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 1000,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'giyu-badge-birthday-2024-cover.jpg',
    owned: false,
    notes: null,
  },
  {
    id: 'giyu-card-sleeve-2024-birthday',
    name_jp: '2024 冨岡義勇の誕生日 アクリルブロマイドホルダー',
    character: 'giyu',
    category: 'card sleeve',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 2000,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'giyu-card-sleeve-birthday-2024-cover.jpg',
    owned: false,
    notes: null,
  },
  // TODO: giyu-bag-2024-birthday — series_id 截斷、image 截斷，請補齊後取消此註解
  // {
  //   id: 'giyu-bag-2024-birthday',
  //   name_jp: '2024 冨岡義勇の誕生日 ケーキ型ポーチ',
  //   character: 'giyu',
  //   category: 'bag',
  //   series_id: 'ufotable-birthday-2024',
  //   price_jpy: 0,
  //   manufacturer: 'ufotable',
  //   release_date: '2024/02/24',
  //   image_cover: '',
  //   owned: false,
  //   notes: null,
  // },
  {
    id: 'giyu-box-2024-birthday',
    name_jp: '2024 冨岡義勇の誕生日 お誕生日BOX',
    character: 'giyu',
    category: 'set',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 10000,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'giyu-box-birthday-2024-cover.jpg',
    owned: false,
    notes: 'ufotableWEBSHOP限定',
  },
  {
    id: 'giyu-acrylic-pop-2024-birthday',
    name_jp: '2024 冨岡義勇の誕生日 スタンディPOP',
    character: 'giyu',
    category: 'acrylic',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 4500,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'giyu-acrylic-pop-birthday-2024-cover.jpg',
    owned: false,
    notes: 'ufotable DINING各店販売限定',
  },
  {
    id: 'giyu-sticker-2024-birthday',
    name_jp: '2024 冨岡義勇の誕生日 ダイカットステッカー',
    character: 'giyu',
    category: 'sticker',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'giyu-sticker-birthday-2024-cover.jpg',
    owned: false,
    notes: 'ポイント景品，ポイント数交換',
  },
  {
    id: 'giyu-melamine-2024-birthday',
    name_jp: '2024 冨岡義勇の誕生日 メラミンプレート',
    character: 'giyu',
    category: 'melamine',
    series_id: 'ufotable-birthday-2024',
    price_jpy: 0,
    manufacturer: 'ufotable',
    release_date: '2024/02/24',
    image_cover: 'giyu-melamine-birthday-2024-cover.jpg',
    owned: false,
    notes: 'ポイント景品，ポイント数交換',
  },

  // ── 鬼滅之刃×明治村 明治村特別任務日誌 ────────────────────────────────

  {
    id: 'shinobu-acrylic-meiji-mura-special-mission-log',
    name_jp: '鬼滅の刃×博物館 明治村 明治村特別任務録 胡蝶しのぶ アクリルスタンド',
    character: 'shinobu',
    category: 'acrylic',
    series_id: 'kimetsu-no-yaiba-meiji-mura-special-mission-log',
    price_jpy: 3850,
    manufacturer: '中外鉱業株式会社',
    release_date: '2026/03/07',
    image_cover: 'shinobu-big-acrylic-meiji-mura-special-mission-log.cover.jpg',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-clear-file-meiji-mura-special-mission-log',
    name_jp: '鬼滅の刃×博物館 明治村 明治村特別任務録 胡蝶しのぶ クリアファイル',
    character: 'shinobu',
    category: 'clear file',
    series_id: 'kimetsu-no-yaiba-meiji-mura-special-mission-log',
    price_jpy: 550,
    manufacturer: '中外鉱業株式会社',
    release_date: '2026/03/07',
    image_cover: 'shinobu-clear-file-meiji-mura-special-mission-log.cover.jpg',
    owned: false,
    notes: null,
  },
  {
    id: 'shinobu-sticker-set-meiji-mura-special-mission-log',
    name_jp: '鬼滅の刃×博物館 明治村 明治村特別任務録 ステッカーセット(5枚入り)',
    character: 'both',
    category: 'sticker',
    series_id: 'kimetsu-no-yaiba-meiji-mura-special-mission-log',
    price_jpy: 2200,
    manufacturer: '中外鉱業株式会社',
    release_date: '2026/03/07',
    image_cover: 'sticker-set-meiji-mura-special-mission-log.cover.jpg',
    owned: false,
    notes: null,
  },
  // TODO: giyu-acrylic-meiji-mura-special-mission-log — 缺 price_jpy，請補齊後取消此註解
  // {
  //   id: 'giyu-acrylic-meiji-mura-special-mission-log',
  //   name_jp: '鬼滅の刃×博物館 明治村 明治村特別任務録 冨岡義勇 アクリルスタンド',
  //   character: 'giyu',
  //   category: 'acrylic',
  //   series_id: 'kimetsu-no-yaiba-meiji-mura-special-mission-log',
  //   price_jpy: 0,
  //   manufacturer: '中外鉱業株式会社',
  //   release_date: '2026/03/07',
  //   image_cover: 'giyu-big-acrylic-meiji-mura-special-mission-log.cover.jpg',
  //   owned: false,
  //   notes: null,
  // },
  {
    id: 'giyu-clear-file-meiji-mura-special-mission-log',
    name_jp: '鬼滅の刃×博物館 明治村 明治村特別任務録 冨岡義勇 クリアファイル',
    character: 'giyu',
    category: 'clear file',
    series_id: 'kimetsu-no-yaiba-meiji-mura-special-mission-log',
    price_jpy: 550,
    manufacturer: '中外鉱業株式会社',
    release_date: '2026/03/07',
    image_cover: 'giyu-clear-file-meiji-mura-special-mission-log.cover.jpg',
    owned: false,
    notes: null,
  },
];
